citizenwallet/app

lib/models/transaction.dart, lib/router/router.dart, lib/screens/wallet/screen.dart, lib/screens/wallet/screen.web.dart, lib/screens/wallet/send_modal.dart, lib/screens/wallet/switch_wallet_modal.dart, lib/screens/wallet/transaction_row.dart, lib/screens/wallet/wallet_actions.dart, lib/services/api/api.dart, lib/services/indexer/signed_request.dart, lib/services/indexer/status_update_request.dart, lib/services/wallet/contracts/derc20.dart, lib/services/wallet/contracts/erc20.dart, lib/services/wallet/contracts/simple_account_factory.dart, lib/services/wallet/models/userop.dart, lib/services/wallet/utils.dart, lib/services/wallet/wallet.dart, lib/state/wallet/logic.dart, lib/state/wallet/selectors.dart, lib/state/wallet/state.dart, lib/widgets/dismissible_modal_popup.dart, pubspec.lock, pubspec.yaml
- sign and submit pending transactions to the indexer
- see incoming and outgoing pending transactions
- show temporary balance based on pending transactions
- slow down update frequency
=> optimistic transaction support

lib/main.dart, lib/models/transaction.dart, lib/screens/wallet/screen.dart, lib/screens/wallet/screen.web.dart, lib/screens/wallet/transaction_row.dart, lib/screens/wallet/wallet_actions.dart, lib/screens/wallet/wallet_scroll_view.dart, lib/state/wallet/logic.dart, lib/state/wallet/state.dart, pubspec.yaml
- show when there is no more to load
- show skeletons of potential transactions
- don't load more if already loading more
=> fixes for infinite transaction list scrolling

lib/models/wallet.dart, lib/screens/wallet/switch_wallet_modal.dart, lib/screens/wallet/wallet_row.dart, lib/state/wallet/logic.dart, lib/state/wallet/state.dart, pubspec.yaml
Task details: https://app.dework.xyz/citizenwallet/app-67595?taskId=0922bbec-6fa9-4f3f-a81d-cf84e9e9f624
=> Display the Smart Contract Account address on the Account list screen

ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/modals/profile/profile.dart, lib/modals/wallet/receive.dart, lib/modals/wallet/send.dart, lib/router/router.dart, lib/screens/account/screen.dart, lib/screens/landing/screen.dart, lib/screens/landing/screen.web.dart, lib/screens/wallet/screen.dart, lib/screens/wallet/screen.web.dart, lib/state/profile/logic.dart, lib/state/profile/state.dart, lib/state/wallet/logic.dart, macos/Podfile.lock, pubspec.yaml
- Allow scanning from within the app
- Deep link into the app and open the send screen
- Supports setting an address, an amount and an alias (for future multi-community)
=> Receive and Profile QR Codes can be scanned from the default device camera as well

lib/modals/wallet/send.dart, lib/screens/transaction/screen.dart, lib/screens/wallet/transaction_row.dart
=> add timestamp in transaction row and modal in local time zone. Fixes #66

lib/screens/wallet/screen.web.dart, pubspec.lock, pubspec.yaml, web/index.html
- show a warning about the wallet being loaded in a web view
- don't load the app if it is in a web view
- refresh the app after a wallet url has been generated
=> Web view warning + Page refresh after wallet generation

ios/Podfile.lock, lib/screens/wallet/wallet_scroll_view.dart, lib/state/wallet/logic.dart, pubspec.lock, pubspec.yaml
updated some dependencies as well
=> Fixed issue with duplicate transactions being displayed while sending

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/screens/landing/screen.dart, lib/screens/wallet/screen.dart, lib/services/credentials/native/android.dart, lib/state/app/logic.dart, pubspec.lock, pubspec.yaml
- Migrated web to v3 url but did not update the native app deep link handling for one specific case where it would need to parse the web url
- Fixed a minor issue with how we parse the query params when scanning a "receive" QR code
=> Fixes for deep linking issues

lib/widgets/communities/community_row.dart
Have fixed svg loading issue for dev mode.
=> hotfix for svg loading faild in dev mode

ios/Runner/AppDelegate.swift, lib/screens/send/send_details.dart, lib/screens/send/send_link_progress.dart, lib/screens/send/send_to.dart, lib/screens/vouchers/screen.dart, lib/screens/vouchers/voucher_row.dart, lib/state/state.dart, lib/state/vouchers/logic.dart, pubspec.lock, test/router_extension.dart
Closes https://github.com/citizenwallet/app/issues/145
https://www.notion.so/citizenwallet/9031a31e02e84cf4899f6c22b5f5d818?v=06c295e3a3df456089be7ca51b62ca55&p=2f2468348d524641846e93c5cafa58d1&pm=s
- After creating a voucher, its address is returned as part of the `pop` method
- The address of the voucher is taken to then update its redeemed/ issued status when returned to the voucher list screen.
- The position of the redeemed/ issued badge is moved to avoid widget cutting
=> Redeem/ Issued state of a voucher 

lib/screens/send/send_details.dart, lib/screens/send/send_link_progress.dart, lib/screens/send/send_progress.dart, lib/screens/send/send_to.dart, lib/widgets/scanner/nfc_modal.dart
- small delay before chained back navigation
=> Fix Black Screen Issue

lib/screens/landing/screen.dart, lib/screens/wallet/screen.dart
if deeplink type is 'onboarding', then load (or create) wallet with alias and do nothing on wallet home screen.
=> 154 deeplink onboard community

lib/screens/send/send_details.dart, lib/screens/send/send_link_progress.dart, pubspec.yaml
Closes  #159 
https://github.com/citizenwallet/app/issues/159
Closes #153 
https://github.com/citizenwallet/app/issues/153
=> Release 1.0.60

lib/screens/wallet/screen.dart
https://www.notion.so/citizenwallet/More-button-needs-haptic-feedback-17073ef57e2b4c83bfb632830c5f03b4?pvs=4
=> haptic feedback when more action button is pressed

lib/screens/wallet/screen.dart, lib/screens/wallet/wallet_actions.dart, lib/screens/wallet/wallet_scroll_view.dart, lib/state/wallet/logic.dart, lib/state/wallet/selectors.dart, lib/state/wallet/state.dart
=> 167 UI blocking loading when opening app

lib/state/wallet/logic.dart, lib/utils/qr.dart, test/services/wallet/qr_test.dart
=> New QR code formats, fixes #174

lib/services/accounts/accounts.dart, lib/services/accounts/native/android.dart, lib/services/db/backup/accounts.dart, lib/services/db/backup/db.dart, lib/state/backup/logic.dart
closes #181 
notion: https://www.notion.so/citizenwallet/fix-the-way-accounts-are-stored-in-the-local-db-encrypted-storage-d1c82583f50040eb901e1274903349cc?pvs=4
new google firebase json file is required for android to complete backup process
=> 181 remove private key from local storage

lib/screens/vouchers/screen.dart, lib/screens/vouchers/voucher_row.dart, lib/state/vouchers/logic.dart, pubspec.yaml
=> 202 voucher amount resets to 0

lib/screens/accounts/screen.dart, lib/screens/wallet/screen.dart, lib/screens/wallet/wallet_actions.dart, lib/services/cache/contacts.dart, lib/services/db/account/contacts.dart, lib/services/db/backup/accounts.dart, lib/services/db/backup/db.dart, lib/services/db/db.dart, lib/services/wallet/wallet.dart, lib/state/app/logic.dart, lib/state/profile/logic.dart, lib/state/profile/state.dart, lib/state/profiles/logic.dart, lib/utils/random.dart, pubspec.lock, pubspec.yaml
=> 204 every new account gets a randomized username

lib/router/router.dart, lib/screens/send/send_to.dart, lib/screens/wallet/screen.dart, lib/state/profiles/logic.dart, lib/state/wallet/logic.dart, lib/utils/qr.dart, pubspec.yaml, test/services/wallet/qr_test.dart
Closes #205 
FORMAT
?sendto=[fridge@wallet.commonshub.brussels](mailto:fridge@wallet.commonshub.brussels)&description=Drinks&amount=3.00
=> 205 improve ux when scanning an address

lib/router/router.dart, lib/screens/transaction/screen.dart, lib/services/db/account/transactions.dart, lib/state/transaction.dart, lib/state/wallet/logic.dart
=> 210 fix background transaction fetch

lib/screens/wallet/screen.dart, lib/services/engine/events.dart, lib/state/wallet/logic.dart, lib/state/wallet/state.dart, lib/state/wallet_connect/logic.dart, lib/state/wallet_connect/state.dart, pubspec.lock
Fixed a bug with disconnect not appearing while connected to sessions
Fixed online/offline banner issue
=> Fixed online/offline and disconnect button issue

lib/l10n/app_en.arb, lib/l10n/app_es.arb, lib/l10n/app_fr.arb, lib/l10n/app_localizations.dart, lib/l10n/app_localizations_en.dart, lib/l10n/app_localizations_es.dart, lib/l10n/app_localizations_fr.dart, lib/l10n/app_localizations_nl.dart, lib/l10n/app_nl.arb, lib/screens/wallet/transaction_row.dart, lib/state/wallet/logic.dart
FIxed issue where the amount for eip681 includes the token decimals
Fixed issue in the transaction list, where burn wasnt shown.
=> Bugfix eip681 decimel

lib/router/router.dart, lib/router/utils.dart, lib/screens/landing/screen.dart, lib/screens/landing/single_community_screen.dart, lib/screens/wallet/screen.dart, lib/state/wallet/logic.dart, lib/utils/qr.dart, test/services/wallet/qr_test.dart
New additions and cleanup
- deep linking clean up
- sendtoUrlWithEIP681Transfer
=> Deeplinking fix - EIP681

test/router/utils_test.dart
Updated test cases to handle sendToParams instead of recieveParams
=> Updated recieveParams to sendTo in test cases

assets/config/v5/communities.json, assets/config/v5/communities.test.json, lib/services/accounts/native/android.dart, lib/services/accounts/native/apple.dart, lib/services/config/config.dart, lib/services/wallet/wallet.dart, lib/services/wallet_connect/wallet_kit.dart, lib/state/deep_link/logic.dart, lib/state/vouchers/logic.dart, lib/state/wallet/logic.dart
Fallback methods added
hidden community fix implemented when migrating
transaction issue fixed after migration
=> v5 migration updated

lib/screens/send/send_progress.dart, lib/screens/send/tip_details.dart, lib/state/wallet/logic.dart, lib/state/wallet/state.dart
=> fixed bug with tipping
